version: "3.8"
services:
  django:
    init: true
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
      DATABASE_URL: sqlite:////app/db.sqlite3
      DEBUG: "True"
    command: runserver
