version: "3.8"
services:
  django:
    init: true
    build: ./django
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
      DATABASE_URL: sqlite:////app/db.sqlite3
      DEBUG: "True"
    command: runserver
  react:
    init: true
    build: ./react
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: start
